package com.roblox.engine.jni.autovalue.le;

import com.github.luben.zstd.BuildConfig;

public class wtzgsqRsIZB {
    public static String AVLhvsrje = "null cannot be used as a map key in JSON at path ";
    public static String CEBL = "onDeviceImageQualityAnalysisLoadLogEvent";
    public static String CXMfpoErnBee = "  filters {\n";
    public static String FeaqHmECN = "Unknown internal Google server error.\nRetry with an exponential backoff. Consider filing a bug if fails consistently.\n";
    public static String HBrLqIATqVo = "autoMirrored";
    public static String HVSe = "/data/local/bin/su";
    public static String IvLP = "value_ was null! Wrap in .nullSafe() to write nullable values.";
    public static String JlEiC = "cmd=";
    public static String LmIkjWirQATb = "Received response with 0 content-length header.";
    public static String MfcKp = "split was not installed ";
    public static String NDsLd = ")";
    public static String PdpSvpoGsSS = "-byte body omitted)";
    public static String PmbkNEbjHSZy = "Fit cannot be used with resize.";
    public static String QCEACtgesm = "request was null";
    public static String QPnnylNgkx = "com.google.android.gms.measurement.internal.AppMeasurementDynamiteService";
    public static String RUQdcDWdFzjFFaI = "Ran off end of other: 0, ";
    public static String SsmdIHF = "sm7325";
    public static String TbXPAFg = "com.google.mlkit.vision.text.aidls.ICommonTextRecognizerCreator";
    public static String UrgGZWqnp = BuildConfig.FLAVOR;
    public static String VQTYu = "Compression context is closed";
    public static String VbXbTyBTHTuy = "other";
    public static String XFnE = "Unexpected data type found for key ";
    public static String XWzSXzXBZEmnFGZ = "db";
    public static String XhymqOpARxPk = "Admost";
    public static String ZpuMfRXyCej = "LoaderManager";
    public static String ffzI = "message";
    public static String hiOLdwLEAYSDhfS = " config";
    public static String jmyDlZtBbyGrPib = " MUST hold lock on ";
    public static String kpyAMFNTm = " is null then group_cnt else 1 end) from (";
    public static String lVTPYfxyZfXM = "Attempt querySubsProduct";
    public static String lXpWG = "Conflicting @FromJson methods:\n    ";
    public static String ldtrOSGBoUIy = "api_force_staging";
    public static String mXsOvapIkrPt = "com.google.android.gms.measurement";
    public static String nlK = "Unexpected response action: ";
    public static String oax = "config_version";
    public static String olensnXQ = "displayName";
    public static String osLOqmYnGV = BuildConfig.FLAVOR;
    public static String pJQCPKl = " requires Google Play services, but they're missing when getting application info.";
    public static String pQNHr = "airplane_mode_on";
    public static String seRxOkv = "a";
    public static String tALKLnk = " description:";
    public static String uMCKAtgAvvpx = "setPreinstallAttribution API called";
    public static String vLiawdmHVd = "index";
    public static String vxE = "ReceiveContent";
    public static String xLU = "this as java.lang.String).getBytes(charset)";
    public static String yCrVNe = "basePlanId";
    public static String ySDeXrVS = "STRING";
    public static String yeiXbuGu = "options";
    public static String zWlGVdAomGIznH = "sslSocket";
}
