package ka.oik;

import com.appsflyer.AppsFlyerProperties;
import com.github.luben.zstd.BuildConfig;

public class UJEa {
    public static String AcJVKeYLjyIAfyM = "EnableRefreshIntegrityTokenProvider";
    public static String AoOJaPvxANP = "Super calls with default arguments not supported in this target, function: close";
    public static String DrgQMykRUVFG = "Field map value '";
    public static String GELEChZY = "}";
    public static String GxfWFobs = "Ok";
    public static String GzlAZ = "com.google.android.gms.appset.internal.IAppSetIdCallback";
    public static String HZtVWNDTcB = "elements";
    public static String IJWDsug = "DEBUG";
    public static String IyedMvGouLO = "eventListener";
    public static String JNBSvt = "null or empty param name in filter. event";
    public static String KRKMCdFuJqIi = AppsFlyerProperties.ONELINK_DOMAIN;
    public static String MHfKSZnJdHo = "Status: CANCELED for module ";
    public static String RNEw = "Downloading ";
    public static String SHPiEJhlb = "Null platformParams";
    public static String SaibuJjzFrzDolQ = "android_native_script";
    public static String UQsnBSNhoIA = BuildConfig.FLAVOR;
    public static String UVBtaXWalF = "app_id,audience_id,filter_id,event_name,data";
    public static String UwC = "_ug";
    public static String VcdXygOTHLSt = "com.google.android.finsky.externalreferrer.GetInstallReferrerService";
    public static String XACnJGYJWHcFWD = "split_id";
    public static String YWjLpgea = "CREATE TABLE events (_id INTEGER PRIMARY KEY, context_id INTEGER NOT NULL, transport_name TEXT NOT NULL, timestamp_ms INTEGER NOT NULL, uptime_ms INTEGER NOT NULL, payload BLOB NOT NULL, code INTEGER, num_attempts INTEGER NOT NULL,FOREIGN KEY (context_id) REFERENCES transport_contexts(_id) ON DELETE CASCADE)";
    public static String ZXZmNaXn = "label";
    public static String aPrjVIDuVFWBW = "rpId";
    public static String arXzaKBlPep = "POSITIVE_BUTTON_CONTENT_DESCRIPTION_RES_ID_KEY";
    public static String cYsNb = ",";
    public static String doMxaDGIEsqiRC = "MORE_TAG";
    public static String dsHruWTeYlV = "af_sub4";
    public static String dsrdbxRyPbAsvVD = "app_id";
    public static String eBOGIvNFGkUC = ", sample rate: ";
    public static String fJLlspYOL = " is less than zero.";
    public static String ffrOqF = "<this>";
    public static String fzjfauylMZ = "Camera2EncoderProfilesProvider";
    public static String ghcVNoHUNT = "Cannot capture crash dump. Cannot find %s environment variable";
    public static String gnK = "GameActivity";
    public static String hJetnrdPs = "<this>";
    public static String iQoUBbokaB = "productKey";
    public static String iksuOTGlsBqLmy = "packageContext";
    public static String oLGkPNIJOQoIYA = "The Play Store app is either not installed or not the official version.\nAsk the user to install an official and recent version of Play Store.\n";
    public static String qEJS = "Camera2CapturePipeline";
    public static String sWPfwavPpwsvnSn = "MeteringRepeating";
    public static String sxSOOLErwm = "isNnApiEnabled";
    public static String whCp = " = 0";
    public static String xGuAzlDqNyzMNK = "Unknown error processing integrity request.\nRetry with an exponential backoff. Consider filing a bug if fails consistently.\n";
    public static String xPgyOHIQlCVo = "LuobuSignupSuspensionNoticeUrl";
}
