package Za.qhkq;

import com.github.luben.zstd.BuildConfig;

public class dHkZSUxHu {
    public static String AcBnzaMlJzBF = "zze";
    public static String CudCwQqkW = "Span count should be at least 1. Provided ";
    public static String DhC = "Only String keys are currently supported in maps, got %s of type %s instead.";
    public static String DjReWqheSgSR = "message == null";
    public static String GRGVfhyJNDhG = "key";
    public static String JEQENtorHDE = "DENIED";
    public static String KjWXWflX = "version";
    public static String LIcUXkjy = "/+$";
    public static String MxzHPvvgPCwW = "fid";
    public static String NnFooU = "peekByte";
    public static String NwJntqSSjxyt = "kotlinx.coroutines.fast.service.loader";
    public static String PmhlJAsNSojKGXb = "available";
    public static String QEWU = "sdk_ver";
    public static String TCboHmFoaVLJkm = "ERROR_MAX_CAMERAS_IN_USE";
    public static String TcuIXELfPIf = "; boundary=";
    public static String TizVXK = "*/";
    public static String WAp = "ON_DEVICE_TRANSLATOR_CLOSE";
    public static String XHWtYCi = "createInstancesForMultiResolutionOutput";
    public static String YijhvuDFcvXEBw = "DialogFragment can not be attached to a container view";
    public static String ZfpStOvem = " cannot be instantiated.";
    public static String aEKkaQN = "Cannot have 2 surfaces for a non-sharing configuration";
    public static String dbUVuFYZ = "deleteSurroundingText: ";
    public static String eZbVLqCMe = BuildConfig.FLAVOR;
    public static String edvxsmBdb = "PUBLIC_QUERY";
    public static String elqwgI = "ACTION_SET_SELECTION";
    public static String fsZZexNgfeuo = "source";
    public static String gAiOwCtR = "onDeviceImageCaptioningInferenceLogEvent";
    public static String gLduudqMYGRt = "ROOM";
    public static String gwgAmWfNcZkuj = "unable to get issues and signature";
    public static String gxvWNLWMG = "UNKNOWN";
    public static String hKhoNpAko = "param";
    public static String hknHqD = "setResolveDeepLinkURLs %s";
    public static String jikuozgAoFoVty = "AnalyticEventDao";
    public static String kXJTSKOSFeltxBp = "toIndex < fromIndex";
    public static String nIlmHxqkknStSyD = "appsflyer_preinstall";
    public static String npHrGYg = "video/*";
    public static String qlcFDYAWncBkVvM = "No keylines defined for ";
    public static String sUjiy = "AndroidCollectThermalThrottling";
    public static String tvRVnkeK = "match";
    public static String umzebcmBgSgL = "Required value was null.";
    public static String vjijaNURg = "Purchase bundle invalid";
    public static String vvOmsuL = "-";
    public static String xOUD = "OPTIONAL_MODULE_CUSTOM_IMAGE_LABELING_INFERENCE";
    public static String xhxrMIYGAFxM = "android.intent.action.BATTERY_LOW";
    public static String zBfNg = "-";
    public static String zXgYIgZK = "TITLE_EXTRA";
}
