package j0.tkB;

import com.github.luben.zstd.BuildConfig;

public class pkcpMQSgx {
    public static String ARWLptPLihRncPZ = "\n  ";
    public static String AXBklnhqiVo = "enablePendingPurchases";
    public static String AlaKvWPeShz = "inferenceDurationStats";
    public static String BMpOp = ")(";
    public static String Btop = "\n";
    public static String CjVHkBTXeglB = "owner";
    public static String EPhRBChmvuzhyp = "pairs";
    public static String FAaWeheg = "_eid";
    public static String FitN = "Unknown";
    public static String FwzzZlBLQdKDmk = "Ad unit id must be a non-empty string";
    public static String HHIViGGAQDQT = "channel_urgent";
    public static String JkLtQrJfVI = "call";
    public static String KFmWknYXW = "_se";
    public static String KSuHjzqacLu = "closed";
    public static String MAQyXEaWhTm = "createCredentialExceptionTypeToException";
    public static String MPVoDYAF = "null";
    public static String OCIkA = "response";
    public static String QDPOYNICp = "PRIORITY";
    public static String QKoOK = "ON_DEVICE_ENTITY_EXTRACTION_CLOSE";
    public static String STzhpCpTWtGe = "<this>";
    public static String VGcEAKVUnXC = "gcm_defaultSenderId";
    public static String VlpMCae = ", dynamicRange=";
    public static String VtTvLfk = "builder";
    public static String XrpD = "AspectFrame";
    public static String ZKdAYX = "AndroidSafeGamepadDisconnectHandler";
    public static String ZOGI = BuildConfig.FLAVOR;
    public static String aLdoYR = "UseMediaPickerProtocolV2";
    public static String acRVSHoTi = "fingerprint";
    public static String aidtzkCdRNBmgCw = "uvBioEnroll";
    public static String bCwKfDEjR = "missingDelimiterValue";
    public static String echaZNuMnFsgR = "initSurfaceView: ...";
    public static String iXmybq = "pixel 6";
    public static String jimKDwKZ = "INAPP_DATA_SIGNATURE";
    public static String jiugluoAiMf = "Failed to clear app set ID generated for App ";
    public static String kBsv = "Phone Number Hint failed";
    public static String mFwTLjCVtg = "common";
    public static String nqnoxUTEsTaR = "af_deeplink";
    public static String oLYTKqlg = "rbx.appshell";
    public static String oVgpKIFBDOS = "latest_copied_version";
    public static String oynlnUOc = "List has more than one element.";
    public static String rXk = "USE_SERVER_STYLES";
    public static String sxaermxJhy = "getTextDirectionHeuristic";
    public static String vbiVrZCBms = "requestBugReportMsg put: ";
    public static String wEaBKuYjVkaeAJJ = "up";
    public static String wdf = "source";
    public static String wsrPXLnK = "app";
    public static String wtvERvY = "Failed requirement.";
    public static String xdE = "Address{";
    public static String yOuGUey = "v1/google/purchase";
    public static String yuKUAULzf = "Expected index to be within 0..size()-1, but was ";
    public static String zHu = "(offset:";
}
